[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter = +<leader_logic.cpp>
build_flags =
    -std=gnu++17

[env:seeed_xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/workloads/scservo.git#1.0.2

lib_extra_dirs =
    ../xiao_soarm/lib

build_flags =
    -Iinclude
    -I../soarm_common
    -I../xiao_soarm/lib/microros
    -I../xiao_soarm/lib/microros/include
    -I../xiao_soarm/lib/microros/include/action_msgs/
    -I../xiao_soarm/lib/microros/include/builtin_interfaces/
    -I../xiao_soarm/lib/microros/include/composition_interfaces/
    -I../xiao_soarm/lib/microros/include/diagnostic_msgs/
    -I../xiao_soarm/lib/microros/include/example_interfaces/
    -I../xiao_soarm/lib/microros/include/geometry_msgs/
    -I../xiao_soarm/lib/microros/include/lifecycle_msgs/
    -I../xiao_soarm/lib/microros/include/micro_ros_msgs/
    -I../xiao_soarm/lib/microros/include/micro_ros_utilities/
    -I../xiao_soarm/lib/microros/include/nav_msgs/
    -I../xiao_soarm/lib/microros/include/rcl/
    -I../xiao_soarm/lib/microros/include/rcl_action/
    -I../xiao_soarm/lib/microros/include/rclc/
    -I../xiao_soarm/lib/microros/include/rclc_lifecycle/
    -I../xiao_soarm/lib/microros/include/rclc_parameter/
    -I../xiao_soarm/lib/microros/include/rcl_interfaces/
    -I../xiao_soarm/lib/microros/include/rcl_lifecycle/
    -I../xiao_soarm/lib/microros/include/rcl_logging_interface/
    -I../xiao_soarm/lib/microros/include/rcutils/
    -I../xiao_soarm/lib/microros/include/rmw/
    -I../xiao_soarm/lib/microros/include/rmw_microros/
    -I../xiao_soarm/lib/microros/include/rmw_microxrcedds_c/
    -I../xiao_soarm/lib/microros/include/rmw_security_common/
    -I../xiao_soarm/lib/microros/include/rosgraph_msgs/
    -I../xiao_soarm/lib/microros/include/rosidl_dynamic_typesupport/
    -I../xiao_soarm/lib/microros/include/rosidl_runtime_c/
    -I../xiao_soarm/lib/microros/include/rosidl_typesupport_c/
    -I../xiao_soarm/lib/microros/include/rosidl_typesupport_interface/
    -I../xiao_soarm/lib/microros/include/rosidl_typesupport_introspection_c/
    -I../xiao_soarm/lib/microros/include/rosidl_typesupport_microxrcedds_c/
    -I../xiao_soarm/lib/microros/include/sensor_msgs/
    -I../xiao_soarm/lib/microros/include/service_msgs/
    -I../xiao_soarm/lib/microros/include/shape_msgs/
    -I../xiao_soarm/lib/microros/include/statistics_msgs/
    -I../xiao_soarm/lib/microros/include/std_msgs/
    -I../xiao_soarm/lib/microros/include/std_srvs/
    -I../xiao_soarm/lib/microros/include/stereo_msgs/
    -I../xiao_soarm/lib/microros/include/test_msgs/
    -I../xiao_soarm/lib/microros/include/tracetools/
    -I../xiao_soarm/lib/microros/include/trajectory_msgs/
    -I../xiao_soarm/lib/microros/include/type_description_interfaces/
    -I../xiao_soarm/lib/microros/include/ucdr/
    -I../xiao_soarm/lib/microros/include/unique_identifier_msgs/
    -I../xiao_soarm/lib/microros/include/uxr/
    -I../xiao_soarm/lib/microros/include/visualization_msgs/
    -DRMW_UXRCE_TRANSPORT=custom
    -DRMW_UXRCE_MAX_HISTORY=4
    -DRMW_UXRCE_MAX_SESSIONS=1
    -DRMW_UXRCE_MAX_TOPICS=2
    -DRMW_UXRCE_MAX_SERVICES=0
    -DRMW_UXRCE_MAX_CLIENTS=0
    -DRMW_UXRCE_STREAM_HISTORY=4
    -DRMW_UXRCE_MAX_PUBLISHERS=2
    -DRMW_UXRCE_MAX_SUBSCRIPTIONS=0
    -DRMW_UXRCE_MAX_TIMERS=0
    -DRMW_UXRCE_MAX_NODES=1
    -L../xiao_soarm/lib/microros
    -lmicroros
